name: flutter_bluetooth_basic_example
description: Demonstrates how to use the flutter_bluetooth_basic plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5

  flutter_bluetooth_basic: any
dev_dependencies:
  flutter_test:
    sdk: flutter
