name: flutter_bluetooth_basic
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 0.1.7
homepage: https://github.com/andrey-ushakov/flutter_bluetooth_basic

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_basic
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin
